### ISSUE TITLE
Criar endpoint para buscar a lista de tipos de eventos (EventTypes)

### ISSUE THREAD

**Issue by saracamilo** [secultce/mapacultural#109]
## **WHAT**

Precisamos criar um novo endpoint para buscar a lista de tipos de eventos.

- [x]  Criar endpoint

- [x]  Criar testes

- [x] Criar documentação

## **WHY**

Porque a API atual não funciona do modo RESTful e possui dificuldades técnicas para receber implementações e mudanças.

## **CHECKLIST**

Precisamos garantir que este endpoint exista:

- [x]  GET /api/v2/events/types

## **TESTS**

Precisamos garantir testes automatizados para o endpoint:

- [x]  Test GET /api/v2/events/types

**Comment by henriquelopeslima** [comment]
Os tipos de objetos são listados por meio de arquivos dentro do diretório de configuração. Esse arquivo é uma exemplo para o objeto de [eventos](https://github.com/secultce/mapacultural/blob/develop/src/conf/event-types.php).
