### ISSUE TITLE
Criar endpoint para buscar os eventos de um espaço

### ISSUE THREAD

**Issue by saracamilo** [secultce/mapacultural#110]
## **WHAT**
Precisamos criar um novo endpoint para buscar a lista de eventos por espaço.

- [x] Criar endpoint
- [x] Criar testes
- [x] Criar documentação

---

## **WHY**
Porque a API atual não funciona do modo RESTful e possui dificuldades técnicas para receber implementações e mudanças.

---

## **CHECKLIST**

Precisamos garantir que este endpoint exista:

- [x] GET `/api/v2/spaces/{id}/events`

---

## **TESTS**

Precisamos garantir testes automatizados para o endpoint:

- [x] Test GET `/api/v2/spaces/{id}/events`

**Comment by henriquelopeslima** [comment]
Estou me desassociando desta issue porque tenho que pegar outras de maior prioridade.
