### ISSUE TITLE
Criar endpoint para buscar as oportunidades de um agente

### ISSUE THREAD

**Issue by saracamilo** [secultce/mapacultural#111]
## **WHAT**
Precisamos criar um novo endpoint para buscar a lista de oportunidades de um agente.

- [x] Criar endpoint
- [x] Criar testes
- [x] Criar documentação

---

## **WHY**
Porque a API atual não funciona do modo RESTful e possui dificuldades técnicas para receber implementações e mudanças.

---

## **CHECKLIST**

Precisamos garantir que este endpoint exista:

- [x] GET `/api/v2/agents/{id}/opportunities`

---

## **TESTS**

Precisamos garantir testes automatizados para o endpoint:

- [x] Test GET `/api/v2/agents/{id}/opportunities``

**Comment by Akellymourab** [comment]
temporariamente pausada
