### ISSUE TITLE
Criar endpoints para Cadastrar e Excluir Selo na API V2

### ISSUE THREAD

**Issue by alessandrofeitoza** [secultce/mapacultural#128]
## **WHAT**
Precisamos criar dois novos endpoints para cadastrar e excluir os selos.

- [x] Criar endpoints
- [x] Criar testes
- [x] Criar documentação
- [ ] Criar validações
- [x] Validar se o novo objeto cadastrado aparece na tela de listar do MapaCultural
- [ ] Validar se ele some ao excluir

---

## **WHY**
Porque a API atual não funciona do modo RESTful e possui dificuldades técnicas para receber implementações e mudanças.

---

## **CHECKLIST**

Precisamos garantir que este endpoint exista:

- [x] POST `/api/v2/seals`
- [x] DELETE `/api/v2/seals/{id}`

---

## **TESTS**

Precisamos garantir testes automatizados para o endpoint:

- [x] Test POST `/api/v2/seals`
- [x] Test  DELETE `/api/v2/seals/{id}`

**Comment by Akellymourab** [comment]
temporariamente bloqueado, necessário alguns ajustes
