### ISSUE TITLE
Criar "Reclame Aqui" do Mapas V5 e V7

### ISSUE THREAD

**Issue by alessandrofeitoza** [secultce/mapacultural#134]
### WHAT
Precisamos de um link nas versões 5 e 7 do Mapas, que permita ao usuário informar sobre um bug/problema encontrado

#### Campos
- Nome da pessoa que está reportando (obrigatório)
- Setor da pessoa que está reportando (obrigatório)
- Descrição do problema (obrigatório)
- Print/Screenshot/Photo do problema (opcional)

### CHECKLIST

- [x] Criar Google Form
- [ ] Adicionar link no V5
- [x] Adicionar link no V7

## ADDITIONAL INFO
Email para administrar o formulario e as respostas: dev@secult.ce.gov.br

Onde adicionar os links:

![Image](https://github.com/secultce/mapacultural/assets/13440490/4980a9a2-be6e-47b4-8a7b-fcf176fec167)

**Comment by Akellymourab** [comment]
TEMPORARIAMENTE PAUSADA

**Comment by alessandrofeitoza** [comment]
Não adicionado na V5 por que atualmente já existe um serviço que faz isso
