### ISSUE TITLE
Criar endpoints para Cadastrar e Excluir Espaço na API V2

### ISSUE THREAD

**Issue by saracamilo** [secultce/mapacultural#137]
## **WHAT**
Precisamos criar dois novos endpoints para cadastrar e excluir os espaços.

- [x] Criar endpoints
- [x] Criar testes
- [x] Criar documentação
- [x] Criar validações
- [x] Validar se o novo objeto cadastrado aparece na tela de listar do MapaCultural
- [x] Validar se ele some ao excluir

---

## **WHY**
Porque a API atual não funciona do modo RESTful e possui dificuldades técnicas para receber implementações e mudanças.

---

## **CHECKLIST**

Precisamos garantir que este endpoint exista:

- [x] POST `/api/v2/spaces`
- [x] DELETE `/api/v2/spaces/{id}`

---

## **TESTS**

Precisamos garantir testes automatizados para o endpoint:

- [x] Test POST `/api/v2/spaces`
- [x] Test  DELETE `/api/v2/spaces/{id}`

**Comment by alessandrofeitoza** [comment]
Closed by #172
