### ISSUE TITLE
Criar documentação dos endpoints de selos

### ISSUE THREAD

**Issue by alessandrofeitoza** [secultce/mapacultural#20]
### WHY

Precisamos garantir que todos os endpoints que envolvem selos na Aplicação estejam documentados.

### HOW

Usando Swagger / OpenAPI

Separe os PRs em partes menores

1: Identificar todos os endpoints e os métodos HTTP deles
2: Descrever a funcionalidade de cada endpoint
3: Descrever o Request Response
4: Descrever o Request Body

### STORY USER

Ao acessar o endereço /docs/index.html o usuário deverá ver a documentação da API do Mapas e tbm os endpoints que envolvem selos

### ADDITIONAL INFO

[Describe here]

### CHECKLIST
- [x] Buscar um selo (`/seal/findOne`)
- [x] Buscar todos os selo (`/seal/find`)
- [x] Criar um selo (`POST /seal/index`)
- [x] Descrever a entidade selo (`/seal/describe`)
- [x] Atualizar um selo (`PATCH /seal/single/:id`)
- [x] Excluir um selo (`DELETE /seal/single/:id`)
- [x] Buscas os tipos de um selo (`/seal/getTypes`)
- [x] Buscas os grupos de tipos de um selo (`/seal/getTypeGroups`)

**Comment by Akellymourab** [comment]
Temporariamente em todo.
