### ISSUE TITLE
Erro ao Tentar Ler a Propriedade "publishedRegistrations" em Oportunidades.

### ISSUE THREAD

**Issue by saracamilo** [secultce/mapacultural#315]
## WHAT

Ao acessar a página de detalhes de novas oportunidades criadas, o seguinte aviso é exibido na tela: **Warning: Attempt to read property "publishedRegistrations" on null in /var/www/src/modules/Opportunities/layouts/parts/opportunity-tab-results.php on line 9** Este aviso indica que o código está tentando acessar a propriedade publishedRegistrations de uma variável que está nula. Precisa ser corrigido para bom funcionamento do Mapas. 

## ADDITIONAL INFO

- [ ] Revisar o código no arquivo opportunity-tab-results.php na linha 9 para identificar onde a variável $opportunity está sendo usada.
- [ ] Identificar a origem da variável $opportunity e onde ela está sendo inicializada.
- [ ] Adicionar uma verificação para garantir que a variável $opportunity não é nula antes de acessar a propriedade publishedRegistrations.

## COMO ESTÁ ATUALMENTE:

![Image](https://github.com/secultce/mapacultural/assets/124682717/d7f57b82-0782-4445-962b-f133c7770f88)

**Comment by henriquelopeslima** [comment]
Eu estou pegando essa issue que estava em blocked, por ter tido alguns avanços investigando esse problema.

**Comment by henriquelopeslima** [comment]
Como já conheciamos esse fluxo e nunca tinha visto tal erro, imaginei que a causa deveria ser por causa de alguma mudança recente. Então, após analisar as mudanças, foi perceptível que esse erro veio nessa pr [aqui](https://github.com/secultce/mapacultural/pull/262).

É fácil comprovar isso, basta executar:
 `git checkout 7471214bc11136560b0c9b02c2362aa15e15aa98`
 
 Dessa forma o estado do código estará no estado alterior ao trabalho do _pull request_ mencionado.
 
 
![image](https://github.com/user-attachments/assets/1debb20f-ed09-4ee7-b89f-8e19bc02c8d9)
> Para realizar esse teste será necessário estar no commit mencionado e com o banco resetado, logo em seguida basta criar um espaço e atrelar uma oportunidade ao espaço criado.

**Comment by henriquelopeslima** [comment]
Esse erro será resolvido com essa issue #375
