### ISSUE TITLE
Complementar a documentação dos endpoints de Eventos

### ISSUE THREAD

**Issue by alessandrofeitoza** [secultce/mapacultural#60]
### WHY

Precisamos garantir que todos os outros endpoints que envolvem os eventos na Aplicação estejam documentados.

- occurrences
- findBySpace
- findByLocation

### HOW

Usando Swagger / OpenAPI

Separe os PRs em partes menores

1: Identificar todos os endpoints e os métodos HTTP deles
2: Descrever a funcionalidade de cada endpoint
3: Descrever o Request Response
4: Descrever o Request Body

### STORY USER

Ao acessar o endereço /docs/index.html o usuário deverá ver a documentação da API do Mapas e tbm os endpoints que envolvem eventos

### ADDITIONAL INFO

URL: http://docs.mapasculturais.org/apidoc/index.html?doctype=api#api-EVENT-findByLocation

### CHECKLIST
- [x] Buscar eventos pleo espaço (`/event/findBySpace`)
- [x] Buscar eventos pela localização (`/event/findByLocation`)
- [x] Buscar as ocorrencias de um evento (`/event/occurrences`)

**Comment by Akellymourab** [comment]
os endpoints abaixo estão com um comportamento fora do esperado, retornando apenas um array vazio 
- /findBySpace 
- /findByLocation
